---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: puppet_apply
  require_puppet_collections: true
  require_chef_for_busser: false
  #modules_path: 

platforms:
  - name: ubuntu-16.04
    provisioner:
      puppet_apt_collections_repo: "http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb"
    driver_config:
      network:
        - ['private_network', {ip: '192.168.34.11'}]


suites:
  - name: default
    provisioner:
      name: puppet_apply
      manifest: nginx.pp
