---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  #name: serverspec
    name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      network:
        - ['private_network', {ip: '192.168.35.11'}]


suites:
  - name: default
    run_list:
            - recipe[kitchenette::default]
